# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  python-sample-deployment
  namespace: default
  labels:
    app:  python-sample
spec:
  selector:
    matchLabels:
      app: python-sample
  replicas: 1
  template:
    metadata:
      labels:
        app:  python-sample
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  python-sample
        image:  chiennguyen196/python-sample:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort:  8000
          name:  python-sample
        env:
        - name:  TEST_ENV
          value:  python-sample
---

